"""
postprocess.py - Repairs BML markdown files generated by the crawler:
  1. Normalizes CRLF -> LF line endings
  2. Fixes image references to use flat relative path (images/<file>)
  3. Promotes standalone function-name lines to ## headers for VS Code anchor navigation
  4. Converts flat parameter table text blocks to proper markdown tables

Format of the crawled parameter table block:
    Parameter
    Data Type
    Description

    param1

    Type
    Description text

    param2
    ...

The header row has no blank lines between the 3 words.
Each data row: param name (blank line) type description.

Automatically runs after every crawl (called from crawler.py __main__).
"""

import os
import re
import sys


def _load_known_function_names(bml_dir):
    try:
        import json
        json_path = os.path.abspath(
            os.path.join(bml_dir, "..", "..", "..", "lang", "intellisense", "bml_functions_api_usage.json")
        )
        if os.path.exists(json_path):
            with open(json_path, encoding="utf-8") as f:
                data = json.load(f)
            return set(data.keys())
    except Exception:
        pass
    return set()


# ---------------------------------------------------------------------------
# 1. Fix image paths -> images/<filename>
# ---------------------------------------------------------------------------

_IMG_RE = re.compile(r'!\[([^\]]*)\]\(([^)]+)\)')


def _fix_image_refs(content):
    def _replace(m):
        alt = m.group(1)
        src = m.group(2)
        if src.startswith("http://") or src.startswith("https://"):
            return m.group(0)
        if "transparent.gif" in src:
            return ""
        filename = os.path.basename(src.split("?")[0])
        return f"![{alt}](images/{filename})"
    return _IMG_RE.sub(_replace, content)


# ---------------------------------------------------------------------------
# 2. Promote standalone function names -> ## headers
# ---------------------------------------------------------------------------

def _promote_function_headers(content, known_names):
    if not known_names:
        return content
    lines = content.split("\n")
    out = []
    for i, line in enumerate(lines):
        stripped = line.strip()
        prev_blank = (i == 0) or (lines[i - 1].strip() == "")
        is_candidate = (
            stripped in known_names
            and prev_blank
            and not stripped.startswith("#")
            and not stripped.startswith("```")
            and not stripped.startswith("|")
            and not stripped.startswith("---")
            and not stripped.startswith("!")
        )
        out.append(f"## {stripped}" if is_candidate else line)
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 3. Convert flat parameter blocks -> markdown tables
#
# Actual format in crawled files (no blank lines between header words):
#
#   Parameter
#   Data Type
#   Description
#
#   param1
#
#   Type
#   Description text.
#
# The block ends at " Return Type:" or " Example:" lines.
# ---------------------------------------------------------------------------

def _convert_param_tables(content):
    lines = content.split("\n")
    out = []
    i = 0
    while i < len(lines):
        # Detect 3-line header: Parameter / Data Type / Description
        if (
            lines[i].strip() == "Parameter"
            and i + 2 < len(lines)
            and lines[i + 1].strip() == "Data Type"
            and lines[i + 2].strip() == "Description"
        ):
            # Collect data rows until we hit Return Type / Example / ## / ---
            j = i + 3
            raw_tokens = []
            while j < len(lines):
                stripped = lines[j].strip()
                if re.match(r'^(Return Type:|Example|## |---)', stripped):
                    break
                raw_tokens.append(stripped)
                j += 1

            non_blank = [t for t in raw_tokens if t]
            table_rows = []
            for idx in range(0, len(non_blank) - 2, 3):
                table_rows.append((non_blank[idx], non_blank[idx + 1], non_blank[idx + 2]))

            if table_rows:
                out.append("")
                out.append("| Parameter | Data Type | Description |")
                out.append("| --- | --- | --- |")
                for param, dtype, desc in table_rows:
                    out.append(f"| `{param}` | {dtype} | {desc} |")
                out.append("")
                i = j  # skip the consumed lines
            else:
                out.append(lines[i])
                i += 1
        else:
            out.append(lines[i])
            i += 1
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def postprocess_bml_docs(bml_dir, known_names=None):
    if known_names is None:
        known_names = _load_known_function_names(bml_dir)

    md_files = [
        os.path.join(bml_dir, f)
        for f in os.listdir(bml_dir)
        if f.endswith(".md")
    ]

    fixed = 0
    for path in md_files:
        with open(path, encoding="utf-8") as f:
            original = f.read()

        # Normalize CRLF -> LF so all processing works uniformly
        content = original.replace("\r\n", "\n").replace("\r", "\n")

        content = _fix_image_refs(content)
        content = _promote_function_headers(content, known_names)
        content = _convert_param_tables(content)
        content = re.sub(r'\n{4,}', '\n\n\n', content)

        if content != original:
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(content)
            print(f"  [postprocess] Fixed: {os.path.basename(path)}")
            fixed += 1

    print(f"[postprocess] Done: {fixed}/{len(md_files)} files updated.")


if __name__ == "__main__":
    _script_dir = os.path.dirname(os.path.abspath(__file__))
    _package_parent = os.path.abspath(os.path.join(_script_dir, ".."))
    if _package_parent not in sys.path:
        sys.path.insert(0, _package_parent)
    _bml_dir = os.path.abspath(os.path.join(_script_dir, "..", "..", "knowledge", "BML"))
    if not os.path.isdir(_bml_dir):
        print(f"ERROR: BML docs directory not found: {_bml_dir}")
        sys.exit(1)
    print(f"[postprocess] Processing: {_bml_dir}")
    postprocess_bml_docs(_bml_dir)